name: otb
description: "tecalaichovalavacatai."
publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^0.13.6
  shared_preferences: ^2.0.15
  hive: ^2.2.3  
  hive_flutter: ^1.1.0
  geolocator: ^9.0.2
   
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/logo.png
    - assets/img/onde.png
